<a href="https://colab.research.google.com/github/descandon88/math-for-machine-learning/blob/main/matrix_operations_for_ml_svd_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Singular Value decomposition (SVD)

As on slides, SVD of matrix A is:

In [2]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [3]:
U,d,VT=np.linalg.svd(A)

In [4]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [5]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [6]:
print(np.transpose(VT))

[[ 0.55798885 -0.82984845]
 [ 0.82984845  0.55798885]]


In [7]:
d

array([8.66918448, 4.10429538])

In [8]:
import numpy as np
from numpy.linalg import svd

# define your matrix as a 2D numpy array
A = np.array([[4, 0], [3, -5]])

U, S, VT = svd(A)



# check that this is an exact decomposition
# @ is used for matrix multiplication in Py3, use np.matmul with Py2
print(U @ np.diag(S) @ VT)

[[ 4.00000000e+00 -1.11271234e-15]
 [ 3.00000000e+00 -5.00000000e+00]]


In [9]:
print("Left Singular Vectors:")
print(U)

Left Singular Vectors:
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]


In [10]:
print("Singular Values:") 
print(np.diag(S))

Singular Values:
[[6.32455532 0.        ]
 [0.         3.16227766]]


In [12]:
print("Right Singular Vectors:") 
print(VT)

Right Singular Vectors:
[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


**OTRA FORMA DE DE CALCULAR SVD**

In [14]:
from numpy.linalg import svd

In [16]:
a = np.array([ [1, -0.8],
             [ 0,1],
             [1,0]
])

In [17]:
print(a);

[[ 1.  -0.8]
 [ 0.   1. ]
 [ 1.   0. ]]


In [19]:
a.shape

(3, 2)

In [22]:
u,s,vT = svd(a,full_matrices=True); 
print(u.shape,s.shape,vT.shape)

(3, 3) (2,) (2, 2)


In [23]:
u,s,vT = svd(a,full_matrices=False); 
print(u.shape,s.shape,vT.shape)

(3, 2) (2,) (2, 2)


In [24]:
u

array([[-7.88170109e-01,  1.87057766e-16],
       [ 3.84473224e-01, -7.80868809e-01],
       [-4.80591530e-01, -6.24695048e-01]])

In [25]:
s

array([1.62480768, 1.        ])

In [26]:
vT

array([[-0.78086881,  0.62469505],
       [-0.62469505, -0.78086881]])

In [27]:
vT.T

array([[-0.78086881, -0.62469505],
       [ 0.62469505, -0.78086881]])