<a href="https://colab.research.google.com/github/descandon88/math-for-machine-learning/blob/main/matrix_operations_for_ml_svd_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Singular Value decomposition (SVD)

As on slides, SVD of matrix A is:

In [4]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [6]:
U,d,VT=np.linalg.svd(A)

In [8]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [10]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [11]:
d

array([8.66918448, 4.10429538])